# Language configuration module for ScanTec
# Supports multiple languages for the application

LANGUAGES = {
    "en": "English",
    "es": "Español",
    "fr": "Français",
    "de": "Deutsch",
    "zh": "中文",
    "ja": "日本語",
}

TRANSLATIONS = {
    "en": {
        "welcome": "Welcome",
        "login": "Login",
        "signup": "Sign Up",
        "username": "Username",
        "password": "Password",
        "email": "Email",
        "role": "Role",
        "dashboard": "Dashboard",
        "profile": "Profile",
        "settings": "Settings",
        "logout": "Logout",
        "theme": "Theme",
        "dark": "Dark",
        "light": "Light",
        "scans": "Scans",
        "archived_scans": "Archived Scans",
        "patient_name": "Patient Name",
        "patient_age": "Patient Age",
        "prediction": "Prediction",
        "confidence": "Confidence",
        "archive": "Archive",
        "delete": "Delete",
        "restore": "Restore",
        "upload": "Upload",
        "analyze": "Analyze",
        "notes": "Notes",
        "comments": "Comments",
        "report": "Report",
        "analytics": "Analytics",
        "audit_logs": "Audit Logs",
        "ehr_export": "EHR Export",
        "admin": "Admin",
        "user": "User",
        "actions": "Actions",
    },
    "es": {
        "welcome": "Bienvenido",
        "login": "Iniciar sesión",
        "signup": "Registrarse",
        "username": "Nombre de usuario",
        "password": "Contraseña",
        "email": "Correo electrónico",
        "role": "Rol",
        "dashboard": "Panel de control",
        "profile": "Perfil",
        "settings": "Configuración",
        "logout": "Cerrar sesión",
        "theme": "Tema",
        "dark": "Oscuro",
        "light": "Claro",
        "scans": "Escaneos",
        "archived_scans": "Escaneos archivados",
        "patient_name": "Nombre del paciente",
        "patient_age": "Edad del paciente",
        "prediction": "Predicción",
        "confidence": "Confianza",
        "archive": "Archivar",
        "delete": "Eliminar",
        "restore": "Restaurar",
        "upload": "Cargar",
        "analyze": "Analizar",
        "notes": "Notas",
        "comments": "Comentarios",
        "report": "Informe",
        "analytics": "Analítica",
        "audit_logs": "Registros de auditoría",
        "ehr_export": "Exportar EHR",
        "admin": "Administrador",
        "user": "Usuario",
        "actions": "Acciones",
    },
    "fr": {
        "welcome": "Bienvenue",
        "login": "Connexion",
        "signup": "S'inscrire",
        "username": "Nom d'utilisateur",
        "password": "Mot de passe",
        "email": "E-mail",
        "role": "Rôle",
        "dashboard": "Tableau de bord",
        "profile": "Profil",
        "settings": "Paramètres",
        "logout": "Déconnexion",
        "theme": "Thème",
        "dark": "Sombre",
        "light": "Clair",
        "scans": "Analyses",
        "archived_scans": "Analyses archivées",
        "patient_name": "Nom du patient",
        "patient_age": "Âge du patient",
        "prediction": "Prédiction",
        "confidence": "Confiance",
        "archive": "Archiver",
        "delete": "Supprimer",
        "restore": "Restaurer",
        "upload": "Télécharger",
        "analyze": "Analyser",
        "notes": "Notes",
        "comments": "Commentaires",
        "report": "Rapport",
        "analytics": "Analytique",
        "audit_logs": "Journaux d'audit",
        "ehr_export": "Exporter EHR",
        "admin": "Administrateur",
        "user": "Utilisateur",
        "actions": "Actions",
    },
    "de": {
        "welcome": "Willkommen",
        "login": "Anmelden",
        "signup": "Registrieren",
        "username": "Benutzername",
        "password": "Passwort",
        "email": "E-Mail",
        "role": "Rolle",
        "dashboard": "Dashboard",
        "profile": "Profil",
        "settings": "Einstellungen",
        "logout": "Abmelden",
        "theme": "Design",
        "dark": "Dunkel",
        "light": "Hell",
        "scans": "Scans",
        "archived_scans": "Archivierte Scans",
        "patient_name": "Patientenname",
        "patient_age": "Patientenalter",
        "prediction": "Vorhersage",
        "confidence": "Zuversicht",
        "archive": "Archivieren",
        "delete": "Löschen",
        "restore": "Wiederherstellen",
        "upload": "Hochladen",
        "analyze": "Analysieren",
        "notes": "Notizen",
        "comments": "Kommentare",
        "report": "Bericht",
        "analytics": "Analytik",
        "audit_logs": "Audit-Protokolle",
        "ehr_export": "EHR exportieren",
        "admin": "Administrator",
        "user": "Benutzer",
        "actions": "Aktionen",
    },
    "zh": {
        "welcome": "欢迎",
        "login": "登录",
        "signup": "注册",
        "username": "用户名",
        "password": "密码",
        "email": "电子邮件",
        "role": "角色",
        "dashboard": "仪表板",
        "profile": "个人资料",
        "settings": "设置",
        "logout": "退出登录",
        "theme": "主题",
        "dark": "深色",
        "light": "浅色",
        "scans": "扫描",
        "archived_scans": "存档的扫描",
        "patient_name": "患者姓名",
        "patient_age": "患者年龄",
        "prediction": "预测",
        "confidence": "信心",
        "archive": "存档",
        "delete": "删除",
        "restore": "恢复",
        "upload": "上传",
        "analyze": "分析",
        "notes": "笔记",
        "comments": "评论",
        "report": "报告",
        "analytics": "分析",
        "audit_logs": "审计日志",
        "ehr_export": "EHR 导出",
        "admin": "管理员",
        "user": "用户",
        "actions": "操作",
    },
    "ja": {
        "welcome": "ようこそ",
        "login": "ログイン",
        "signup": "サインアップ",
        "username": "ユーザー名",
        "password": "パスワード",
        "email": "メール",
        "role": "役割",
        "dashboard": "ダッシュボード",
        "profile": "プロフィール",
        "settings": "設定",
        "logout": "ログアウト",
        "theme": "テーマ",
        "dark": "ダーク",
        "light": "ライト",
        "scans": "スキャン",
        "archived_scans": "アーカイブされたスキャン",
        "patient_name": "患者名",
        "patient_age": "患者年齢",
        "prediction": "予測",
        "confidence": "確度",
        "archive": "アーカイブ",
        "delete": "削除",
        "restore": "復元",
        "upload": "アップロード",
        "analyze": "分析",
        "notes": "メモ",
        "comments": "コメント",
        "report": "レポート",
        "analytics": "分析",
        "audit_logs": "監査ログ",
        "ehr_export": "EHRエクスポート",
        "admin": "管理者",
        "user": "ユーザー",
        "actions": "アクション",
    },
}

def get_text(key, language="en"):
    """Get translated text for a given key and language"""
    if language not in TRANSLATIONS:
        language = "en"
    return TRANSLATIONS.get(language, TRANSLATIONS["en"]).get(key, key)

def get_language_list():
    """Get list of available languages"""
    return LANGUAGES
